"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { cn, npaoColor, phaseColor } from "@/lib/utils";
import type { NPAOClass, FourDsPhase } from "@/types";
import { Sparkles, Loader2, CheckCircle2, ArrowRight, Brain, Target, Zap } from "lucide-react";

function simulatePALIntake(rawDescription: string) {
  const lower = rawDescription.toLowerCase();
  const isAutomation = /automate|workflow|integration|pipeline|n8n|zapier/.test(lower);
  const isDashboard = /dashboard|report|analytics|metrics|kpi|chart/.test(lower);

  let projectType = "General Project";
  if (isAutomation) projectType = "Automation";
  else if (isDashboard) projectType = "Dashboard / Reporting";

  const projectName = rawDescription.slice(0, 60).replace(/\n/g, " ").trim() + (rawDescription.length > 60 ? "..." : "");

  const tasks: { title: string; description: string; npao_class: NPAOClass; phase: FourDsPhase; estimated_minutes: number; done_when: string; build_prompt: string }[] = [
    { title: "Define input schema and data sources", description: "Identify all inputs, their formats, and where they come from", npao_class: "N", phase: "PreD", estimated_minutes: 30, done_when: "All input sources documented", build_prompt: `Map every data input for ${projectName}` },
    { title: "Confirm tool access and API credentials", description: "Verify all required tools are accessible", npao_class: "N", phase: "PreD", estimated_minutes: 45, done_when: "All required API keys confirmed and tested", build_prompt: `For ${projectName}: list every tool needed and confirm access` },
    { title: "Resolve scope boundaries", description: "Clarify in-scope vs out-of-scope", npao_class: "A", phase: "D1", estimated_minutes: 20, done_when: "Scope document with explicit in/out boundaries", build_prompt: `Write scope boundary doc for ${projectName}` },
    { title: `Build the ${projectType.toLowerCase()} core`, description: `Implement the primary deliverable`, npao_class: "P", phase: "D2", estimated_minutes: 90, done_when: "Core functionality working end-to-end", build_prompt: `Build the core of ${projectName}` },
    { title: "Write tests and validate outputs", description: "Test all scenarios and verify quality", npao_class: "P", phase: "D2", estimated_minutes: 45, done_when: "All test cases pass", build_prompt: `Create test plan for ${projectName}` },
    { title: "Add monitoring and alerts", description: "Set up monitoring", npao_class: "O", phase: "D4", estimated_minutes: 30, done_when: "Alerts configured for failures", build_prompt: `Set up monitoring for ${projectName}` },
    { title: "Create documentation", description: "Document for future maintainers", npao_class: "O", phase: "D4", estimated_minutes: 30, done_when: "Docs cover setup, operation, troubleshooting", build_prompt: `Write documentation for ${projectName}` },
  ];

  return { projectName, description: `${projectType} — generated by PAL`, phase: "PreD" as FourDsPhase, tasks };
}

export default function IntakePage() {
  const router = useRouter();
  const [input, setInput] = useState("");
  const [processing, setProcessing] = useState(false);
  const [result, setResult] = useState<ReturnType<typeof simulatePALIntake> | null>(null);
  const [saved, setSaved] = useState(false);

  async function handleIntake() {
    if (!input.trim()) return;
    setProcessing(true);
    await new Promise((r) => setTimeout(r, 1500));
    setResult(simulatePALIntake(input));
    setProcessing(false);
  }

  async function handleSaveAndBuild() {
    if (!result) return;
    setProcessing(true);
    const project = await api.createProject({ name: result.projectName, description: result.description, phase: result.phase });
    for (let i = 0; i < result.tasks.length; i++) {
      const t = result.tasks[i];
      await api.createTask({ project_id: project.id, title: t.title, npao_class: t.npao_class, phase: t.phase, description: t.description, estimated_minutes: t.estimated_minutes, done_when: t.done_when });
    }
    setSaved(true);
    setTimeout(() => router.push(`/projects/${project.id}`), 1500);
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-8"><h1 className="text-3xl font-bold mb-1 flex items-center gap-3"><Sparkles className="w-7 h-7 text-blue-400" />AI Intake</h1><p className="text-zinc-400">PAL (Prompt Abstraction Layer) — describe your project in plain English. ROSTR compiles it into a structured build plan with NPAO-classified tasks.</p></div>
      <div className="mb-8 p-4 rounded-xl border border-zinc-800 bg-zinc-900/50">
        <div className="flex items-center justify-center gap-2 text-sm text-zinc-500">
          {["L1: Intent", "L2: Composition", "L3: Optimization", "L4: Compilation", "L5: Runtime"].map((stage, i) => (
            <div key={stage} className="flex items-center gap-2"><span className="px-2 py-1 rounded bg-zinc-800 text-xs">{stage}</span>{i < 4 && <span>→</span>}</div>
          ))}
        </div>
      </div>
      {!result && (
        <div className="space-y-4">
          <textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder={`Describe your project in plain English...\n\nExamples:\n"Build a HubSpot automation that enriches new contacts"\n"Create a weekly pipeline dashboard"\n"Set up Slack notifications for deal updates"`} rows={6} className="w-full px-4 py-4 rounded-xl border border-zinc-700 bg-zinc-800/50 text-white placeholder:text-zinc-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50 resize-none text-lg" />
          <button onClick={handleIntake} disabled={!input.trim() || processing} className="px-6 py-3 rounded-xl bg-gradient-to-r from-blue-500 to-violet-500 text-white font-semibold hover:from-blue-600 hover:to-violet-600 transition-all inline-flex items-center gap-2 disabled:opacity-50">
            {processing ? <Loader2 className="w-5 h-5 animate-spin" /> : <Brain className="w-5 h-5" />}{processing ? "Compiling..." : "Compile with PAL"}
          </button>
        </div>
      )}
      {result && !saved && (
        <div className="space-y-6 animate-fade-in">
          <div className="p-6 rounded-xl border border-emerald-500/30 bg-emerald-500/5">
            <div className="flex items-center gap-2 mb-4"><CheckCircle2 className="w-5 h-5 text-emerald-400" /><span className="font-semibold text-emerald-400">PAL Compilation Complete</span></div>
            <h2 className="text-xl font-bold mb-2">{result.projectName}</h2>
            <p className="text-zinc-400 text-sm mb-4">{result.description}</p>
            <span className={cn("px-2 py-0.5 rounded text-xs font-medium border", phaseColor(result.phase))}>{result.phase}</span>
            <span className="text-sm text-zinc-500 ml-2">{result.tasks.length} tasks generated</span>
          </div>
          <h3 className="font-semibold flex items-center gap-2"><Target className="w-4 h-4 text-blue-400" />Generated Tasks (NPAO Classified)</h3>
          {result.tasks.map((task, i) => (
            <div key={i} className="p-4 rounded-lg border border-zinc-800 bg-zinc-900/50">
              <div className="flex items-start gap-3">
                <span className={cn("px-2 py-0.5 rounded text-xs font-bold border shrink-0 mt-0.5", npaoColor(task.npao_class))}>{task.npao_class}</span>
                <div className="flex-1"><div className="font-medium text-sm">{task.title}</div><div className="text-xs text-zinc-500 mt-1">{task.description}</div><div className="flex items-center gap-3 mt-2 text-xs text-zinc-600"><span>{task.estimated_minutes} min</span><span>{task.phase}</span></div></div>
              </div>
            </div>
          ))}
          <div className="flex gap-3 pt-4">
            <button onClick={handleSaveAndBuild} disabled={processing} className="px-6 py-3 rounded-xl bg-white text-black font-semibold hover:bg-zinc-200 transition-all inline-flex items-center gap-2 disabled:opacity-50">{processing ? <Loader2 className="w-5 h-5 animate-spin" /> : <Zap className="w-5 h-5" />}Save & Start Building <ArrowRight className="w-4 h-4" /></button>
            <button onClick={() => { setResult(null); setInput(""); }} className="px-6 py-3 rounded-xl border border-zinc-700 text-zinc-300 font-medium hover:bg-zinc-800">Start Over</button>
          </div>
        </div>
      )}
      {saved && (
        <div className="text-center py-16 animate-fade-in">
          <CheckCircle2 className="w-12 h-12 mx-auto mb-4 text-emerald-400" />
          <h2 className="text-2xl font-bold mb-2">Project Created!</h2>
          <p className="text-zinc-400 mb-4">All {result?.tasks.length} tasks saved with NPAO classification.</p>
        </div>
      )}
    </div>
  );
}
